name: Deploy Obsidian vault to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          path: vault/
      - name: Checkout Quartz
        uses: actions/checkout@v4
        with:
          repository: jackyzha0/quartz
          path: quartz/
          # ref: v5.0.0
      - name: Move configuration to Quartz
        run: mv vault/quartz.config.yaml quartz/
      - name: Update baseUrl in configuration
        run: 'sed --in-place "s/baseUrl:.*/baseUrl: ${{ github.repository_owner }}.github.io\/${{ github.event.repository.name }}/" quartz.config.yaml'
        working-directory: quartz/
      - name: Remove license
        run: rm vault/LICENSE
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
        working-directory: quartz/
      - name: Install plugins
        run: npx quartz plugin install --from-config
        working-directory: quartz/
      - name: Build site
        run: npx quartz build --directory ../vault/
        working-directory: quartz/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
